# Intentation must be follow while typing
name: Python flask with firebase CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest  # GitHub Actions Runner Images
        steps:
            - name: Checkout code on runner machine
              uses: actions/checkout@v4  # It will chekout you repository under workplace

            
            - name: Run some commands
              run: |   # | For Run multiple command with diffrent lines
                  python3 -m venv flask-firebase-app
                  source flask-firebase-app/bin/activate
                  pip install -r requirements.txt
                  pip install --upgrade pip setuptools
                  pytest tests/test_app.py
                  PYTHONWARNINGS=ignore FLASK_ENV=production python3 app.py
                  deactivate