# Intentation must be follow while typing
name: Python flask with firebase CI/CD Pipeline

on:
    push:
        branches:
            - staging  # Set branch name

jobs:
    build:
        runs-on: ubuntu-latest  # GitHub Actions Runner Images
        steps:
            - name: Checkout code on runner machine
              uses: actions/checkout@v4  # It will chekout you repository under workplace



            - name: Setup Environment
              uses: actions/setup-python@v4
              with:
                python-version: '3.8'  # Set your python version
              env:
                FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
                FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
                FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
                FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
                FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
                FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
                FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
                FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
                FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
                FIREBASE_SERVICE_ACCOUNT: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'

                run: |
                  pip install -r requirements.txt
                  pip install --upgrade pip
                  python app.py 
                